import type { Metadata } from "next";
import Header from "@/modules/Header/Header";
import { Locale } from "@/shared/types";
import { getDictionary } from "@/shared/utils";
import Footer from "@/modules/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  const { locale } = await params;
  const { header, footerNav } = await getDictionary(locale);

  return (
    <div className="flex flex-col min-h-[100%]">
      <Header translation={header} />
      <main className="bg-background-gray h-full flex-1">{children}</main>
      <Footer translation={footerNav} />
    </div>
  );
}
